import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopContact from './components/TopContact'
import Navbar from './components/Navbar'
import Header from './components/Header'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopContact />
        <div className='sticky top-0 z-50'>
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
